### PR TITLE
Add CircleCI compatibility

### PR DESCRIPTION
**Pull request by rafaelje**
Hi, in this PR we add compatibility to CircleCI with these tasks:

- update version code
- update version name
- generate changelog
- build
- instrumented test
- deploy with fastlane beta and production rollout
- deploy with github releaser
- generate documentation with javadoc
- generate documentation code coverage
- generate documentation android test
- publish changelog on gh-pages
- publish documentation on gh-pages

### CODE REVIEW

**Comment by ajsb85** [comment]
@rafaelje CircleCI don't have gradle preintalled?

**Review by hectorerb — APPROVED** [review]
Fine 👍

**Comment by rafaelje** [comment]
@ajsb85 Circleci works with dockers and the Android Image that they have today don't have preinstalled gradle, we can create a custom cache to store it later, this is a better way

**Comment by ajsb85** [comment]
@rafaelje Ok, lets improve it later. 👍🏻

**Pull request merged**
