### PR TITLE
Add Silent SMS Ping

### LINKED ISSUE #3: Silent Ping SMS
Hi, @rafaelje 

Please, integrate this feature into the Mobile Admin Dashboard of the MDM platform.

**Ping request by SMS**

Source code base:
https://github.com/itds-consulting/android-silent-ping-sms

Best regards.

### PR DESCRIPTION
**Pull request by CamposErik**
### Changes description
Including the Silent SMS ping feature in the android-mdm-dashboard.
It need to import the numberphone from the glpi-java-library.

giphy

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [x] Docs have been added/updated

### Estimated time

|Assignee|:tomato:|
|:---|:---:|
|@CamposErik|15|

### References

Closes #3, #70
Related #3 
Depends on #N/A

### CODE REVIEW

**Comment by ghost** [comment]
There were the following issues with this Pull Request

* Commit: 52f581b25ce068a38abde7d544341c06e2b2acf1
  - ✖ message may not be empty
  - ✖ type may not be empty


You may need to [change the commit messages][ref] to comply with the repository contributing guidelines.

--------

🤖 This comment was generated by [**commitlint[bot]**][repo]. Please report issues [here][issues].

Happy coding!

[ref]: https://help.github.com/articles/changing-a-commit-message/
[repo]: https://github.com/z0al/commitlint-bot
[issues]: https://github.com/z0al/commitlint-bot/issues

**Comment by ajsb85** [comment]
Hi, @CamposErik 
This is an invalid scope:
`feat(): create the login layout`
If your changes are envolved with the login features, your scope is `login`
`feat(login): create the login layout`
This commit message is also invalid:
`refactor(devices):change sms silent ping location`
Add a space after the symbol `:`
If you don't know how to amend the commit messages.
Ping me or Thierry on Telegram to Help you
Thank you.

**Comment by CamposErik** [comment]
Hi @Ivans51 y @rafaelje,
could you review this PR to merge it later, it missing to import the numberphones from the library.

**Review by ajsb85 — CHANGES_REQUESTED** [review]
Hi, @CamposErik 
Here is how to fix the DCO status 
https://git.io/fp7T5

**Review by ajsb85 — COMMENTED** [review]
Hi, @CamposErik 
Change the Email to IMEI.
Because the list of SIM Cards provide phone numbers and IMEI, no associate SIM Card with emails.
I approve it, but try to granulate better the the features, for a faster review of other team members.

**Review by ajsb85 — DISMISSED** [review]

**Review by ajsb85 — APPROVED** [review]

**Pull request merged**
