### PR TITLE
Rename folders for normalization

### PR DESCRIPTION
**Pull request by Naylin15**
### Changes description
Rename folders of development section for normalization

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [x] Docs have been added/updated

### References

Related #55 
Closes #N/A

### CODE REVIEW

**Review by ajsb85 — CHANGES_REQUESTED** [review]
Hi, @Naylin15 
Please squash this multiple commit message:
`docs(coverage): update code coverage and test reports`

**Review by ajsb85 — COMMENTED** [review]
Hi, @Naylin15 
There are commits from the user "Flyve MDM"
In such cases we push commits from the user @teclib-bot.

**Comment by Naylin15** [comment]
Hi,

I'll change the user

Though the commits will be removed before the merge of this PR, they are to test the workflow works as expected

**Review by ajsb85 — APPROVED** [review]

**Comment by ajsb85** [comment]
Hi, @Naylin15 
Again, misconfiguration of the git with the user from the CI.

image

```bash
GITHUB_EMAIL=apps@teclib.com
git config --global user.email $GITHUB_EMAIL
git config --global user.name "Teclib"
```

**Comment by Naylin15** [comment]
All right, I'll change it right away 👍

**Review by ajsb85 — APPROVED** [review]

**Review by ajsb85 — APPROVED** [review]

**Review by rafaelje — APPROVED** [review]
Reviewed 👍

**Pull request merged**
