### PR TITLE
Dashboard progress

### PR DESCRIPTION
**Pull request by rafaelje**
## Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: [Conventional Commit](http://conventionalcommits.org/)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue # N/A

## What is the new behavior?
Add screens for:

- Devices
- Fleets
- Files
- Users

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ajsb85** [comment]
This branch has conflicts that must be resolved

**Comment by rafaelje** [comment]
Working on it

**Review by ajsb85 — DISMISSED** [review]
Reviewed

**Comment by rafaelje** [comment]
@hectorerb @ajsb85 it's ready to merge please review when you can

**Review by hectorerb — APPROVED** [review]
Reviewed

**Pull request merged**
